version: '3'
services:
  accounts-service:
    build: .
    image: sept23s2/accounts-service:s3945703
    ports:
      - "8080:8080"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: accountsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8081:8081"

volumes:
  db-data:
